#!/bin/sh
mode=`uci get system.upgrade.mode`
start_minute=`uci get system.upgrade.start_minute`
start_hour=`uci get system.upgrade.start_hour`

exist=`cat /etc/crontabs/root | grep regular_task`

if [[ "$mode" == "1" ]];then
		if [[ -n "$exist" ]]; then
			sed -i '/regular_task/d' /etc/crontabs/root
		fi
		echo "$start_minute $start_hour * * * /usr/sbin/timer_control.sh auto_upgrade" >> /etc/crontabs/root
		/etc/init.d/cron restart
		exit 0
else
	sed -i '/auto_upgrade/d' /etc/crontabs/root
	/etc/init.d/cron restart
	exit 0
fi
