#!/bin/sh
# Notice: $ACTION = ONLINE/OFFLINE; $IP; $MAC; $IFTYPE

CONFIG="reward_device"
TYPE="user"
section_name=${MAC//:/_}
sharedwifi_enable=$(uci get sharedwifi.wifidog.enable)
interface="`cfg_phic -g wifi ifname sharewifi ifname`"

if [ $sharedwifi_enable -eq 1 ]; then
	IFTYPE=`cat /proc/net/statsPerIp | grep "$MAC" | awk '{print $8}'`
	rate=$(uci get $CONFIG.$section_name.rate)
	if [ "$ACTION" = "ONLINE" ] && [ "$IFTYPE" = "4" ]; then
		ret=`iptables -t mangle -nvL sharedwifi_limit_chain | grep $IP | head -n 1`
		if [ -n "$ret" ]; then
			logger -t DEBUG "rule has exist"
			return 
		fi
		logger -t DEBUG "$ACTION, $IFTYPE."
		if [ $rate -gt 0 ]; then
			logger -t DEBUG "add '$IP' limit rule...."
			iptables -t mangle -w -A sharedwifi_limit_chain --src $IP -m hashlimit --hashlimit-name src_$section_name \
				--hashlimit ${rate}kb/s --hashlimit-burst ${rate}kb/s --hashlimit-mode srcip -j RETURN >/dev/null 2>&1
			iptables -t mangle -w -A sharedwifi_limit_chain --src $IP -j DROP >/dev/null 2>&1
			
			iptables -t mangle -w -A sharedwifi_limit_chain --dst $IP -m hashlimit --hashlimit-name dst_$section_name \
				--hashlimit ${rate}kb/s --hashlimit-burst ${rate}kb/s --hashlimit-mode dstip -j RETURN >/dev/null 2>&1
			iptables -t mangle -w -A sharedwifi_limit_chain --dst $IP -j DROP >/dev/null 2>&1
		fi
	elif [ "$ACTION" = "OFFLINE" ]; then
		if [ $rate -gt 0 ]; then
			logger -t DEBUG "del '$IP' limit rule...."
			iptables -t mangle -w -D sharedwifi_limit_chain --src $IP -m hashlimit --hashlimit-name src_$section_name \
				--hashlimit ${rate}kb/s --hashlimit-burst ${rate}kb/s --hashlimit-mode srcip -j RETURN >/dev/null 2>&1
			iptables -t mangle -w -D sharedwifi_limit_chain --src $IP -j DROP >/dev/null 2>&1
			
			iptables -t mangle -w -D sharedwifi_limit_chain --dst $IP -m hashlimit --hashlimit-name dst_$section_name \
				--hashlimit ${rate}kb/s --hashlimit-burst ${rate}kb/s --hashlimit-mode dstip -j RETURN >/dev/null 2>&1
			iptables -t mangle -w -D sharedwifi_limit_chain --dst $IP -j DROP >/dev/null 2>&1
		fi
	fi
fi
